openai_api_key = "YOUR_OPENAI_API_KEY"
[supabase]
url = "https://your-project.supabase.co"
anon_key = "YOUR_SUPABASE_ANON_KEY"
service_key = "YOUR_SUPABASE_SERVICE_ROLE_KEY"
[stripe]
secret_key = "YOUR_STRIPE_SECRET_KEY"
price_id = "PRICE_ID"
success_url = "https://your-app-url"
cancel_url = "https://your-app-url"
