openai_api_key = "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"

[supabase]
url = "https://ypvglsyxzdoknccshpnk.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlwdmdsc3l4emRva25jY3NocG5rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1MDc5ODEsImV4cCI6MjA2MzA4Mzk4MX0.8tDcB1Q2qeURnCs7N8wpE49J7YrJummAh3USGFFrlHE"

[stripe]
public_key = "pk_live_51RKqe6DhjTMRdYuYokXCNqOuJlNLzdfbN7t2I1Kqs0jMy0wwhhIDunCRuxxIPIcjShiplzl7WuWGiNe292eOma6r00ENlGTZ03"
secret_key = "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"
automatic_tax_enabled = true

