openai_api_key = "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"

[supabase]
url = "https://ypvglsyxzdoknccshpnk.supabase.co"
service_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlwdmdsc3l4emRva25jY3NocG5rIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0NzUwNzk4MSwiZXhwIjoyMDYzMDgzOTgxfQ.RTvuwh-PtbhQ-4KSf2qHmsX-acVpkFRBYWx3voGz6eM"

[stripe]
secret_key  = "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"
price_id    = "price_1RRZu7DhjTMRdYuY6ZgCIAF4"
success_url = "https://dmvtutor.streamlit.app"
cancel_url  = "https://dmvtutor.streamlit.app"
