openai_api_key = "sk-proj_5iO7MLPMBp_lAX7xWPv_vDqkoX9G6DqrF9WTDscA4aIOw-h2wcxFj2RcdtYZQ7jmh1PuI207OXT3BlbkFJOQJztHgUZJQytkqiQuVXelvzAggZ_VOAzZkVnY1apad-PDxjgNzM2EVHO7jEvKCOIefwoqcrsA"

[supabase]
url = "https://ypvglsyxzdoknccshpnk.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlwdmdsc3l4emRva25jY3NocG5rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1MDc5ODEsImV4cCI6MjA2MzA4Mzk4MX0.8tDcB1Q2qeURnCs7N8wpE49J7YrJummAh3USGFFrlHE"
service_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlwdmdsc3l4emRva25jY3NocG5rIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0NzUwNzk4MSwiZXhwIjoyMDYzMDgzOTgxfQ.RTvuwh-PtbhQ-4KSf2qHmsX-acVpkFRBYWx3voGz6eM"

[stripe]
secret_key  = "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"
price_id    = "price_1RTR0hDhjTMRdYuYCvKfOoO6"
success_url = "https://dmvtutor.streamlit.app"
cancel_url  = "https://dmvtutor.streamlit.app"
